# Generated by Django 3.0.7 on 2020-06-22 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('side_effects_list', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Very Severe', 'Very Severe'), ('Worst Pain Possible', 'Worst Pain Possible')], max_length=200)),
                ('duration_in_hours', models.FloatField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
                ('side_effect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.SideEffect')),
            ],
        ),
        migrations.CreateModel(
            name='MedReminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
                ('medication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Medication')),
            ],
        ),
        migrations.CreateModel(
            name='MedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('number_of_doses', models.FloatField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
                ('medication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Medication')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='side_effects',
            field=models.ManyToManyField(blank=True, to='users.SideEffect'),
        ),
        migrations.CreateModel(
            name='CustomerMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_for', models.CharField(blank=True, max_length=200, null=True)),
                ('dosage', models.CharField(blank=True, max_length=200, null=True)),
                ('morning', models.BooleanField(default=False)),
                ('midday', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('bedtime', models.BooleanField(default=False)),
                ('medication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Medication')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='medications',
            field=models.ManyToManyField(blank=True, to='users.CustomerMedication'),
        ),
        migrations.AddField(
            model_name='customer',
            name='my_side_effects_list',
            field=models.ManyToManyField(blank=True, to='users.SideEffect'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
