# Generated by Django 3.0.7 on 2020-07-04 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 16, 59, 46, 970526, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='medlog',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 16, 59, 46, 976509, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 16, 59, 46, 975481, tzinfo=utc), null=True),
        ),
    ]
