# Generated by Django 3.0.7 on 2020-06-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SideEffects',
            new_name='SideEffect',
        ),
    ]
