# Generated by Django 3.0.7 on 2020-06-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomlog',
            name='side_effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.SideEffect'),
        ),
    ]
