# Generated by Django 3.0.7 on 2020-06-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200620_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Very Severe', 'Very Severe'), ('Worst Pain Possible', 'Worst Pain Possible')], max_length=200)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
                ('effect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.SideEffect')),
            ],
        ),
    ]
