# Generated by Django 3.0.7 on 2020-06-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200621_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='side_effects',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='side_effects_list',
        ),
    ]
