# Generated by Django 3.0.7 on 2020-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200621_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='sideeffects',
            field=models.ManyToManyField(to='users.SideEffect'),
        ),
    ]
