# Generated by Django 3.0.7 on 2020-06-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='effect',
            new_name='side_effect',
        ),
        migrations.AddField(
            model_name='log',
            name='durarion_in_hours',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='treatmentFor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
