# Generated by Django 3.0.7 on 2020-06-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_medication_sideeffects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='sideeffects',
            new_name='side_effects',
        ),
    ]
