# Generated by Django 3.0.7 on 2020-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_medication_side_effects_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='medications',
            field=models.ManyToManyField(blank=True, to='users.CustomerMedication'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='my_side_effects_list',
            field=models.ManyToManyField(blank=True, to='users.SideEffect'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='side_effects',
            field=models.ManyToManyField(blank=True, to='users.SideEffect'),
        ),
    ]
