# Generated by Django 3.0.7 on 2020-06-21 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200620_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedReminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer')),
                ('medication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Medication')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='time',
            field=models.ManyToManyField(to='users.Time'),
        ),
    ]
