# Generated by Django 3.0.7 on 2020-06-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='medications',
            field=models.ManyToManyField(null=True, to='users.Medication'),
        ),
    ]
