# Generated by Django 3.0.7 on 2020-06-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200621_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='time',
        ),
        migrations.AddField(
            model_name='medication',
            name='bedtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='midday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='morning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='side_effects_list',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='medications',
            field=models.ManyToManyField(to='users.Medication'),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
